auto: true
server: true
markdown: kramdown
pygments: false
title: akkunchoi.github.com
sitename: akkunchoi.github.com
author:
  name: Akiyoshi Tanaka
  email: akkunchoi@gmail.com

# for rss
description: This site is a information for development written by akkunchoi
fullurl: http://akkunchoi.github.com

permalink: /:categories/:title.html

tag_title_prefix: "["
tag_title_suffix: "]"
