#!/bin/sh

day=`date +%Y-%m-%d`

file="_posts/$day-$1.md"

if [ -f $file ]; then
  echo "$file exists."
  echo "Overwrite? [Y/n] >"
  read INPUT
  if [ $INPUT != "Y" ]; then
    exit
  fi
fi

cat <<EOD > $file
---
layout: posts
title: $1
tags: etc
---

EOD

vim "_posts/$day-$1.md"

